version: 0.0.1
achievements:
  - achievement:
      name: Moderator
      icon: https://raw.githubusercontent.com/vauntdev/example/main/.vaunt/closer.png
      description: Awarded to assignees of an issue marked as moderator.
      triggers:
        - trigger:
            actor: assignees
            action: issue
            condition: closed = true & labels in ['moderator']
  - achievement:
      name: Helpful Commenter
      icon: https://raw.githubusercontent.com/vauntdev/example/main/.vaunt/every_bit_counts.png
      description: Create a helpful comment on an issue approved by moderators
      triggers:
        - trigger:
            actor: author
            action: issue_comment
            condition: reaction in ['THUMBS_UP'] & reactor in ['jeff1010322']
